Fix ambiguity for "=" operator involving String and Unbounded_String
Author: Eric Botcazou <ebotcazou@adacore.com>

The usage of the "=" operator with an overloaded left operand with String
and Unbounded_String interpretations and a String right operand is illegal
because it is ambiguous.  This will be diagnosed by an enhanced compiler:

 lsp-ada_handlers.adb:5589:65:
   error: ambiguous expression (cannot resolve "=")
 lsp-ada_handlers.adb:5589:65:
   error: possible interpretation at a-strunb.ads:248
 lsp-ada_handlers.adb:5589:65:
   error: possible interpretation in package Standard

TN: V112-041